import type { IconType } from "react-icons";
import { FaAws } from "react-icons/fa6";
import {
  SiApache,
  SiBabel,
  SiBootstrap,
  SiCloudflare,
  SiDocker,
  SiExpress,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGnubash,
  SiJavascript,
  SiJest,
  SiMongodb,
  SiMongoose,
  SiMui,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiOpenapiinitiative,
  SiOpenjdk,
  SiPm2,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiRedux,
  SiSocketdotio,
  SiSpringboot,
  SiStorybook,
  SiTestinglibrary,
  SiTypescript,
  SiVercel,
  SiVite,
} from "react-icons/si";
import { TbBroadcast, TbCube } from "react-icons/tb";

/** Default icon when no brand glyph exists (in-house or niche tooling). */
export const technologyStackDefaultFallbackIcon: IconType = TbCube;

const technologyStackIconByLabel: Readonly<Record<string, IconType>> = {
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  Java: SiOpenjdk,
  ReactJS: SiReact,
  "React Native": SiReact,
  Vite: SiVite,
  NextJS: SiNextdotjs,
  ExpressJS: SiExpress,
  "Spring Boot (JPA)": SiSpringboot,
  "Vanilla JS": SiJavascript,
  "Web APIs": SiJavascript,
  "Material UI": SiMui,
  Bootstrap: SiBootstrap,
  NativeBase: TbCube,
  "react-native-paper": SiMui,
  NodeJS: SiNodedotjs,
  Babel: SiBabel,
  Docker: SiDocker,
  Apache: SiApache,
  PM2: SiPm2,
  Nginx: SiNginx,
  Git: SiGit,
  GitHub: SiGithub,
  Bash: SiGnubash,
  MongoDB: SiMongodb,
  "Mongoose ORM": SiMongoose,
  PostgreSQL: SiPostgresql,
  Prisma: SiPrisma,
  AWS: FaAws,
  "Vercel Functions": SiVercel,
  CDN: SiCloudflare,
  Jest: SiJest,
  "React Testing Library": SiTestinglibrary,
  Redux: SiRedux,
  "Context API": SiReact,
  "Radio (in-house Pub/Sub engine)": TbBroadcast,
  "Socket.io": SiSocketdotio,
  "Design Systems": SiStorybook,
  "RESTful APIs": SiOpenapiinitiative,
  "GitHub Actions": SiGithubactions,
  "Vercel Deployment": SiVercel,
};

export function resolveTechnologyStackIcon(label: string): IconType {
  return technologyStackIconByLabel[label] ?? technologyStackDefaultFallbackIcon;
}
